name: health_ai_assistant
description: "随身AI健康管家"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.6.0  # 先不加，等下再加

  deepseek_api: ^0.1.2
  image_picker: ^1.2.1
  http_parser: ^4.1.2
  mime: ^2.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true